TEXT_ALL_LEVELS_COMPLETED  = "CONGRATULATIONS! ALL LEVELS HAVE BEEN COMPLETED!";
TEXT_SCORE                 = "LEVEL SCORE: ";

TEXT_NEXT_LEVEL  = "CONGRATULATIONS!";
TEXT_LEVEL       = "SELECT LEVEL";

TEXT_GAME_OVER   = "YOU CRASHED YOUR CAR!";
TEXT_TOTAL_SCORE = "TOTAL SCORE: ";
TEXT_CREDITS_DEVELOPED = "Developed by";
var TEXT_PRELOADER_CONTINUE = "START";

TEXT_MOVE_DESKTOP  = "USE ARROW KEYS TO STEER AND DRIVE YOUR CAR";
TEXT_MOVE_MOBILE   = "STEER";
TEXT_MOVE_MOBILE1  = "BREAK/\nREVERSE";
TEXT_MOVE_MOBILE2  = "ACCELERATOR";
TEXT_RESET = "ARE YOU SURE? ALL YOUR SAVED PROGRESS WILL BE DELETED!";
TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";
